### ISSUE TITLE
Requirements from Lars

### ISSUE THREAD

**Issue by larswirzenius** [Minoru/plentyfs#3]
I will use this issue to record the requirements, when I have time. I'll also submit PRs to add them to the subplot.

For now, consider this a placeholder.

**Comment by larswirzenius** [comment]
Sorry, that took me a lot longer than intended.

My use for this will be to try my backup program on very large data sets: can it handle an enormous amount of data at all. For this, I care less about performance than whether it works at all. A FUSE file system is likely to be slower than real disks anyway.

The test setup I have in mind is:

* start plentyfs to emulate a filesystem with, say, a petabyte of generated data
* back up the plentyfs filesystem with my backup program to my backup server
  * the backup program splits the data it reads from plentyfs into chunks and uploads each chunk to the server
  * configure the backup server to not actually store the chunks, only their metadata
    * I don't have the disk space to store a petabyte, or I wouldn't need plentyfs

If I can finish the backup, I have at least some confidence the my backup system can handle a petabyte.

Thus, I'd like to be able to configure plentyfs at least in the following ways:

* how many files there are
* size of each file
* are all files in one flat directory or are they split into several levels of directories

**Comment by Minoru** [comment]
> Sorry, that took me a lot longer than intended.

No problem! That gave me some time to brush up on RNGs, hashes, and ciphers, and think about possible implementations.

The following questions are all over the place. I promise they'll become more coherent once I've understood the problem space a bit better.

> how many files there are

Can it be "inodes" instead of "files"? I trust you know the difference, but for the benefit of others who might read this: inode represents not just files, but also directories and links. It'd be possible to ask for an FS with N inodes and get nothing but directories with empty subdirectories; no files.

Also, is it okay if that number is treated as a statistical mean rather than an exact number? In other words, if we fixed that parameter and varied the seed, PlentyFS would generate different filesystems, and if we took an average file count over all of them, we'd get the parameter back; but each individual filesystem could have fewer or more files than requested.

> size of each file

Does that mean you want *all* files to be of the same, fixed size? I doubt you mean to specify the size of *each* file in the FS, as there could be billions.

Alternatively, can this be treated as a statistical mean, just like the number of files?

> are all files in one flat directory or are they split into several levels of directories

Do you want *precise* control over the hierarchy, e.g. via a file in a format similar to `ls -lnR`? (I doubt you do, as you'll need a separate tool to generate such a file; but that approach has some benefits).

Alternatively, can this requirement be fulfilled by two knobs that control minimum and maximum depth of the hierarchy?

Also, a few prompts for more requirements:

- any constraints on the file names? If not, I'd just generate random byte sequences (excluding NUL and slash) of fixed size ((MAX_PATH - mountpoint.len() - 1) / max_depth - 1);
- any constraints on the contents of the files? You'd probably want to test deduplication somehow. PlentyFS could limit randomness of the file blocks to increase the chances of two blocks being the same. (Unfortunately I can't think of a way to test deduplication of variable-size blocks.)

**Comment by larswirzenius** [comment]
> > how many files there are
> 
> Can it be "inodes" instead of "files"? I trust you know the difference, but for the benefit of others who might read this: inode represents not just files, but also directories and links. It'd be possible to ask for an FS with N inodes and get nothing but directories with empty subdirectories; no files.

Actually, having slept on this another night, I think I don't care about number of files, only about total amount of data, approximate maximum size of a file, and shape of directory structure. Thus I'd like to be able to say "give me a pretend filesystem with one petabyte of data, no file larger than a hundred gigabytes, and at most one thousand entries per directory".

After that, if file sizes vary from empty to a hundred gigabytes, that's fine. If there is a directory structure that's several levels deep, that's also fine.

Basically, whatever is easier to implement is probably OK for me.

> Also, is it okay if that number is treated as a statistical mean rather than an exact number? In other words, if we fixed that parameter and varied the seed, PlentyFS would generate different filesystems, and if we took an average file count over all of them, we'd get the parameter back; but each individual filesystem could have fewer or more files than requested.

Sure, statistical mean is OK in all cases.

> Does that mean you want _all_ files to be of the same, fixed size? I doubt you mean to specify the size of _each_ file in the FS, as there could be billions.

I'm OK with all files being of the same, fixed size, or they can vary if that's easier to implement. I don't want to, at this point, specify each file separately.

>     * any constraints on the file names? If not, I'd just generate random byte sequences (excluding NUL and slash) of fixed size ((MAX_PATH - mountpoint.len() - 1) / max_depth - 1);

No constraints on file names. My backup solution has to deal with any valid Unix filename. If the kernel accepts it, so shall the backup program.

>     * any constraints on the contents of the files? You'd probably want to test deduplication somehow. PlentyFS could limit randomness of the file blocks to increase the chances of two blocks being the same. (Unfortunately I can't think of a way to test deduplication of variable-size blocks.)

I'm OK with any content, and PlentyFS doesn't need to try to either produce duplicate data or avoid producing any. If it's easier to implement, non-duplicate data is A-OK for me.

**Comment by Minoru** [comment]
I filed some issues for the things I'd like to implement first, and I'd start knocking them off one by one now. If any of them seem badly worded, please jump in and correct me!

**Comment by larswirzenius** [comment]
Yup, they look good!
